name: Build Result

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create or update comment for image tags
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Docker image tag(s) pushed:
            ```text
            ${{ steps.docker_meta.outputs.tags }}
            ```

            Labels added to images:
            ```text
            ${{ steps.docker_meta.outputs.labels }}
            ```
          edit-mode: replace
    